name: 'crypto_data_platform'
version: '1.0.0'
config-version: 2

profile: 'crypto_data_platform'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

models:
  crypto_data_platform:
    silver:
      +materialized: view
      +schema: silver 