crypto_data_platform:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      user: postgres
      password: postgres
      dbname: crypto_data_platform
      schema: public
      threads: 4 